name: Create Permanent Signing Key

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate permanent debug keystore
        run: |
          keytool -genkeypair -v \
            -keystore debug.keystore \
            -storepass android \
            -alias androiddebugkey \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Computer Master,O=Soumen Mondal,C=IN"

      - name: Convert keystore to Base64
        run: |
          base64 -w 0 debug.keystore > debug-keystore-base64.txt

      - name: Upload signing key
        uses: actions/upload-artifact@v4
        with:
          name: Computer-Master-Permanent-Signing-Key
          path: debug-keystore-base64.txt
          retention-days: 7
